name: pex
description: All in one Personal Expenses Manager.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.3+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #  Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.9.1

  #  Easyloading
  flutter_easyloading: ^3.0.5

  #  Currency picker
  currency_picker: ^2.0.16

  #  Shared Preferences
  shared_preferences: ^2.2.0

  #  Emoji Keyboard
  emoji_picker_flutter: ^1.6.1

  #  URL Launcher
  url_launcher: ^6.1.13

  #  Firebase Phone Auth
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.1.1
  sms_autofill: ^2.3.0

  # Check for internet
  connectivity_plus: ^4.0.2

  # Splash Screen
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  color_dark: "#FFFFFF"
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/logo/logoWithPadding.png
    icon_background_color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logoWithPadding.png
    - assets/logo/logoWithoutPadding.png
    - assets/logo/logoGoogle.png
